name: 'Gomerge Action'
description: 'Bulk merge and approve pull requests on a schedule'
author: 'Cian Gallagher'
branding:
  icon: 'git-merge'
  color: 'green'
inputs:
  repository:
    description: 'The repository this actions should run against. Default is the current repository.'
    required: true
  github_token:
    description: 'Github token which has access to given repository.'
    required: true
  labels: 
    description: 'List of labels that should only be approved/merged.'
    required: false
    default: ""
  approve:
    description: 'Set this option if you only want to approve pull requests and not merge them. Default is false.'
    required: false
    default: false
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.repository }}
    - ${{ inputs.github_token }}
    - ${{ inputs.labels }}
    - ${{ inputs.approve }}
